theory RPxTPTP imports Main begin

SML_import
\<open>
  structure PolyML = struct
     val pointerEq = pointer_eq
  end
\<close>
SML_file "./src/Random.sig"
SML_file "./src/Random.sml"
SML_file "./src/Portable.sig"
SML_file "./src/PortablePolyml.sml"
SML_file "./src/RPx.sml"
SML_file "./src/Useful.sig"
SML_file "./src/Useful.sml"
SML_file "./src/Lazy.sig"
SML_file "./src/Lazy.sml"
SML_file "./src/Ordered.sig"
SML_file "./src/Ordered.sml"
SML_file "./src/Map.sig"
SML_file "./src/Map.sml"
SML_file "./src/KeyMap.sig"
SML_file "./src/KeyMap.sml"
SML_file "./src/Set.sig"
SML_file "./src/Set.sml"
SML_file "./src/ElementSet.sig"
SML_file "./src/ElementSet.sml"
SML_file "./src/Sharing.sig"
SML_file "./src/Sharing.sml"
SML_file "./src/Stream.sig"
SML_file "./src/Stream.sml"
SML_file "./src/Heap.sig"
SML_file "./src/Heap.sml"
SML_file "./src/Print.sig"
SML_file "./src/Print.sml"
SML_file "./src/Parse.sig"
SML_file "./src/Parse.sml"
SML_file "./src/Name.sig"
SML_file "./src/Name.sml"
SML_file "./src/NameArity.sig"
SML_file "./src/NameArity.sml"
SML_file "./src/Term.sig"
SML_file "./src/Term.sml"
SML_file "./src/Subst.sig"
SML_file "./src/Subst.sml"
SML_file "./src/Atom.sig"
SML_file "./src/Atom.sml"
SML_file "./src/Formula.sig"
SML_file "./src/Formula.sml"
SML_file "./src/Literal.sig"
SML_file "./src/Literal.sml"
SML_file "./src/Thm.sig"
SML_file "./src/Thm.sml"
SML_file "./src/Proof.sig"
SML_file "./src/Proof.sml"
SML_file "./src/Rule.sig"
SML_file "./src/Rule.sml"
SML_file "./src/Normalize.sig"
SML_file "./src/Normalize.sml"
SML_file "./src/Model.sig"
SML_file "./src/Model.sml"
SML_file "./src/Problem.sig"
SML_file "./src/Problem.sml"
SML_file "./src/TermNet.sig"
SML_file "./src/TermNet.sml"
SML_file "./src/AtomNet.sig"
SML_file "./src/AtomNet.sml"
SML_file "./src/LiteralNet.sig"
SML_file "./src/LiteralNet.sml"
SML_file "./src/Subsume.sig"
SML_file "./src/Subsume.sml"
SML_file "./src/KnuthBendixOrder.sig"
SML_file "./src/KnuthBendixOrder.sml"
SML_file "./src/Rewrite.sig"
SML_file "./src/Rewrite.sml"
SML_file "./src/Units.sig"
SML_file "./src/Units.sml"
SML_file "./src/Clause.sig"
SML_file "./src/Clause.sml"
SML_file "./src/Active.sig"
SML_file "./src/Active.sml"
SML_file "./src/Waiting.sig"
SML_file "./src/Waiting.sml"
SML_file "./src/Resolution.sig"
SML_file "./src/Resolution.sml"
SML_file "./src/Tptp.sig"
SML_file "./src/Tptp.sml"
SML_file "./src/Options.sig"
SML_file "./src/Options.sml"
SML_file "./src/rpx_toplevel.sml"

end